export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Provider } from "@/components/ui/provider"

export default function RootLayout({children}) {
  "use client"
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
